import { mkdirSync, writeFileSync } from 'node:fs';

// Resolve paths relative to this script, independent of the working directory.
try {
  process.loadEnvFile(new URL('../.env', import.meta.url));
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
}

// Export only explicitly selected public settings, never the whole environment.
const apiBaseUrl = process.env.API_BASE_URL?.trim().replace(/\/+$/, '');
if (!apiBaseUrl) {
  throw new Error('Set API_BASE_URL in Frontend/.env (copy .env.example) or the process environment.');
}
const url = new URL(apiBaseUrl);
if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password || url.search || url.hash) {
  throw new Error('API_BASE_URL must be an HTTP(S) URL without credentials, query parameters or a fragment.');
}

const outputDirectory = new URL('../src/environments/', import.meta.url);
mkdirSync(outputDirectory, { recursive: true });
writeFileSync(new URL('environment.ts', outputDirectory),
  '// Generated by scripts/generate-env.mjs. Edit .env, then restart or rebuild.\n' +
  `export const environment = ${JSON.stringify({ apiBaseUrl }, null, 2)} as const;\n`);
